### PR TITLE
Feat: server testing

### PR DESCRIPTION
**Pull request by dilekyalcin**
- Updated MongoDb connection.
- The 'index.py' file is accessed to access the 'app' object with 'sys.path'.
- auth, user, post, comment, like tests have been added.

### CODE REVIEW

**Comment by aahmetdurmaz** [comment]
LGTM

**Comment by gecicidegisken** [comment]
image
*reminder for conventional commits*

**Comment by hilaldedek** [comment]
LGTM

**Comment by softwareVirus** [comment]
I think there is some code repetition like:
```py
assert 'id' in first_post
    assert 'title' in first_post
    assert 'content' in first_post
    assert 'author' in first_post
    assert 'firstname' in first_post
    assert 'lastname' in first_post
    assert 'likeCount' in first_post
    assert 'likes' in first_post
    assert 'created_at' in first_post
```
You may control this situations under the function to avoid code repetition

**Pull request merged**
