### PR TITLE
The backend has been dockerized

### PR DESCRIPTION
**Pull request by dilekyalcin**
- Dockerfile configures a Docker container for an application based on Python 3.9. It copies the application code inside, installs the necessary dependencies, and exposes port 5000 to the outside world.
- The Docker Compose file provides the development environment for the microblogging application by running the front and back-end services in Docker containers. It also provides access to a database such as MongoDB.
- The entry point index.py of the Flask application has been updated to bind to 0.0.0.0 when running the development server, allowing external access.

### CODE REVIEW

**Comment by hilaldedek** [comment]
Reviewed ✅

**Comment by aahmetdurmaz** [comment]
LGTM!!

**Comment by softwareVirus** [comment]
I think the env variables like mongodb_url and secret keys should not be added in docker-compose.yml file. You can specify in the document that these variables must be given by the user.

**Comment by dilekyalcin** [comment]
@softwareVirus I agree. I am using a cloud service, and I have created a user in MongoDB that can read and write but cannot directly connect from the admin. I used to store this information in a config file, but I ignored it, so I need to share it with the user later. Honestly , I did it this way to avoid dealing with it 😂 I could also have ${Mongo_URL} imported from the Environment section, but since I needed to share it in the readme, I preferred to write it here directly. But the Secret key could be made like that.

**Pull request closed without merging**
